### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by grappler** [mhmli/mhm-flickrsettings#1]
Hey Mark, I hope you don't mind me giving some feedback...
- When you are saving the settings to the database the data is not being sanitized. You could do something simple like adding `esc_attr` so you have `register_setting( 'media', 'flickr_key', 'esc_attr' )` or create your own function to check the key length and escape any html.
- And then on the other side I would escape the data before output `get_option( 'flickr_key' )` as you cannot trust the data from the database.
- Have you thought about internationalizing the text?
- So to not add multiple rows to the `wp_options` I would use a single option like `mhm_flickr_settings` and add the key, secret and user id in an array. Most of the time you will call all of the options at the same time. This way the settings are also protected from conflict as another plugin may define the same options names.

Let me know if you would like me to create a PR. :smile:

**Comment by markhowellsmead** [comment]
Good feedback, thanks. I'll add it to the next version!

**Comment by markhowellsmead** [comment]
Sanitization resolved in 1.1.0. Other issues next time ;)
